export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_ERROR = "APPLY_JOB_ERROR";

export const GET_ALL_JOB = "GET_ALL_JOB";
export const GET_ALL_JOB_ERROR = "GET_ALL_JOB_ERROR";
